workflows:
  android-debug:
    name: Android Debug Workflow
    instance_type: mac_mini_m1
    scripts:
      - name: Build APK
        script: |
          export JAVA_HOME=$JAVA_HOME_21
          export PATH=$JAVA_HOME/bin:$PATH
          cd aykut
          chmod +x gradle/wrapper/gradle-wrapper.properties
          gradle assembleDebug
    artifacts:
      - aykut/app/build/outputs/apk/debug/*.apk
