workflows:
  android-debug:
    name: Android Debug Workflow
    environment:
      android_sdk: default
    scripts:
      - name: Build APK
        script: |
          cd uygulama
          chmod +x gradle
          ./gradlew assembleDebug
    artifacts:
      - uygulama/build/outputs/apk/debug/*.apk
git add codemagic.yaml 
git commit -m 'İlk iş akışını ekle' 
git push
